bempp/bempp-rs

quadrature/src/duffy/triangle.rs
quadrature/src/simplex_rules.rs
quadrature/src/types.rs

Wrote a unified interface for Duffy rules on triangles.

Refactored triangle duffy rules.

---

.github/ISSUE_TEMPLATE/element.md
.github/ISSUE_TEMPLATE/fmm.md
.github/ISSUE_TEMPLATE/quadrature.md
.github/ISSUE_TEMPLATE/traits.md
.github/ISSUE_TEMPLATE/tree.md

This will give you the option of picking which crate your issue is related to and automatically tag it

Add issue templates for main crates

---

tree/src/implementations/impl_morton.rs
tree/src/implementations/impl_single_node.rs
tree/src/types/morton.rs

- Add iterator implementation
- Add test

ENH: Make MortonKeys an iterator

---

tree/src/implementations/impl_domain.rs
tree/src/implementations/impl_morton.rs

- Fix a bug in morton encoding
- Add a small threshold to domain calculations so that no points lie on boundary
- Add new tests for this functionality

FIX: Morton encoding

---

.github/workflows/run-tests.yml
.gitignore
fmm/Cargo.toml
python/test/test_dependencies.py

Add test that dependencies use consistent versions

---

element/src/cell.rs
element/src/element.rs
element/src/element/lagrange.rs
element/src/element/raviart_thomas.rs
element/src/map.rs

This vastly reduces the number of warnings displayed when running cargo test

Reduce number of warnings (from element crate)

---

.github/workflows/deploy-docs.yml
.github/workflows/run-tests.yml
README.md

This will make the latest docs from the main branch available at https://rusty-fast-solvers.github.io/solvers/

Deploy documentation to github pages

---

find_examples.py

Not running examples on 3 processes for now due to #66

fix NPROCESSES in examples

---

element/src/cell.rs
element/src/cell/cells_0d.rs
element/src/cell/cells_2d.rs
element/src/cell/cells_3d.rs
element/src/element/lagrange.rs
element/src/element/raviart_thomas.rs
grid/Cargo.toml
grid/examples/grid.rs
grid/src/grid.rs
grid/src/shapes.rs
quadrature/src/simplex_rules.rs
traits/src/cell.rs
traits/src/element.rs

Refactor connectivity of higher order grids

---

element/src/element.rs
element/src/element/lagrange.rs
element/src/element/raviart_thomas.rs
element/src/map.rs
traits/src/element.rs

- Remove consts from element trait (closes #16)
- Add documentation to element
- Simplify TabulatedData by not storing the element

Remove consts from element trait

---

element/src/element.rs
element/src/element/lagrange.rs
element/src/element/raviart_thomas.rs
element/src/map.rs
tools/src/arrays.rs
traits/src/element.rs

Use Array2D and Array4D from bempp_tools instead of a mixture of element's own Tabulated data structure and flat arrays

Use Array2D and Array4D in element

---

grid/src/grid.rs
grid/src/parallel_grid.rs
tools/src/arrays.rs
traits/src/grid.rs

This will be needed to assemble the singular parts of operators.
This implementation can be vastly improved by using sparse matrices but this will allow us to get started
Close #87.

Add function to get adjacent cells

---

.github/workflows/deploy-docs.yml

Improve docs index

---

.github/workflows/run-tests.yml
bem/examples/singular_assemble.rs
grid/examples/curved_cells.rs
grid/examples/grid.rs
hyksort/examples/redundant.rs
hyksort/examples/unique.rs

Add `cargo clippy --examples` to CI.
Fixed clippy errors in examples

Run clippy on examples

---

.github/workflows/run-tests.yml
.github/workflows/run-weekly-tests.yml

Only run on stable for each PR.
Add weekly scheduled runs with beta and nightly

Reduce number of CI runs

---

.github/workflows/run-tests.yml
bem/src/assembly/dense.rs
element/src/polynomials.rs
fmm/src/fmm.rs
fmm/src/linalg.rs
grid/src/grid.rs
tools/src/arrays.rs
tree/src/implementations/impl_domain.rs
tree/src/implementations/impl_morton.rs
tree/src/implementations/impl_single_node.rs

Add `cargo clippy --tests` to CI.
Fixed clippy errors in tests

Run clippy on tests

---

element/src/polynomials.rs
grid/src/grid.rs
tools/src/arrays.rs
tree/src/implementations/impl_morton.rs

Fixed #111.
Added size assert when creating an array from data to catch similar bugs in future

Correct polynomial test

---

fmm/src/charge.rs
fmm/src/constants.rs
fmm/src/field_translation/hadamard.rs
fmm/src/field_translation/source.rs
fmm/src/field_translation/source_to_target.rs
fmm/src/field_translation/target.rs
fmm/src/fmm.rs
fmm/src/interaction_lists.rs
fmm/src/types.rs
traits/src/field.rs
traits/src/fmm.rs
tree/src/implementations/helpers.rs
tree/src/implementations/impl_single_node.rs

* Add a fully adaptive FMM for comparison with uniformly FMM.
* Add missing docs for various functions
* Parametrise FMM tests to test all functionality.

ENH: Adaptive FMM

---

.github/workflows/docs.yml
.github/workflows/run-tests.yml
.github/workflows/run-weekly-tests.yml
.github/workflows/style-checks.yml

Update rust toolchain CI action

---

field/Cargo.toml

CLN: Remove DashMap depdency in Field

---

bem/benches/assembly_benchmark.rs
bem/src/assembly.rs
bem/src/assembly/batched.rs

Reduces time for singular assembly of 2048×2048 matrix on my desktop from 1.59s to 216ms

Speed up singular assembly

---

bem/Cargo.toml
bem/benches/assembly_benchmark.rs
bem/src/assembly/batched.rs

Implement assembly of singular terms into CSR matrix

---

kernel/Cargo.toml
kernel/out.txt
kernel/src/helmholtz_3d.rs
kernel/src/laplace_3d.rs
kernel/src/lib.rs
traits/src/kernel.rs
traits/src/types.rs

Helmholtz kernel

---

grid/examples/flat_triangle_grid.rs
grid/examples/mixed_grid.rs
grid/examples/single_element_grid.rs

Add grid creation examples

---

bem/Cargo.toml
bem/benches/assembly_benchmark.rs
bem/src/assembly.rs
bem/src/assembly/batched.rs
bem/src/assembly/batched/hypersingular.rs
bem/src/assembly/fmm_tools.rs
bem/src/function_space.rs
bem/tests/compare_to_bempp_cl.rs
bem/tests/fmm.rs
element/src/element.rs
element/src/element/lagrange.rs
element/src/element/raviart_thomas.rs
grid/src/flat_triangle_grid/grid.rs
grid/src/mixed_grid/geometry.rs
grid/src/mixed_grid/topology.rs
grid/src/single_element_grid/geometry.rs
grid/src/single_element_grid/topology.rs
grid/src/traits.rs
grid/src/traits_impl.rs
grid/tests/grid.rs
traits/src/bem.rs
traits/src/element.rs
traits/src/grid/grid_type.rs

Resolves #220. Progress towards #221.

Implement assembly on quadrilateral cells

---

bem/tests/mixed_assembly.rs

Add tests for mixed assembly

---

bem/src/assembly/batched.rs

Remove filtering of cells in batched assembly

---

examples/flat_triangle_grid.rs
examples/mixed_grid.rs
examples/single_element_grid.rs
src/bem/assembly.rs
src/grid/flat_triangle_grid.rs
src/grid/flat_triangle_grid/builder.rs
src/grid/flat_triangle_grid/grid.rs
src/grid/flat_triangle_grid/io.rs
src/grid/mixed_grid.rs
src/grid/mixed_grid/builder.rs
src/grid/mixed_grid/geometry.rs
src/grid/mixed_grid/grid.rs
src/grid/mixed_grid/io.rs
src/grid/mixed_grid/topology.rs
src/grid/shapes.rs
src/grid/single_element_grid.rs
src/grid/single_element_grid/builder.rs
src/grid/single_element_grid/geometry.rs
src/grid/single_element_grid/grid.rs
src/grid/single_element_grid/io.rs
src/grid/single_element_grid/topology.rs
src/grid/traits_impl.rs
tests/grid.rs
tests/io.rs
tests/mixed_assembly.rs

- remove WrappedGrid
- remove "Serial" from grid struct names

Tidy up grid code

---

examples/test_parallel_grid.rs
src/grid/flat_triangle_grid/grid.rs
src/grid/flat_triangle_grid/parallel.rs
src/grid/mixed_grid.rs
src/grid/mixed_grid/builder.rs
src/grid/mixed_grid/grid.rs
src/grid/mixed_grid/parallel.rs
src/grid/mixed_grid/topology.rs
src/grid/single_element_grid.rs
src/grid/single_element_grid/builder.rs
src/grid/single_element_grid/grid.rs
src/grid/single_element_grid/parallel.rs
src/grid/single_element_grid/topology.rs
src/traits/types/cell.rs
tests/fmm.rs

Implement parallel single element and mixed grids

---

examples/test_parallel_grid.rs
src/assembly/common.rs
src/grid/common.rs
src/grid/flat_triangle_grid/grid.rs
src/grid/flat_triangle_grid/parallel.rs
src/grid/mixed_grid.rs
src/grid/mixed_grid/builder.rs
src/grid/mixed_grid/grid.rs
src/grid/mixed_grid/parallel.rs
src/grid/mixed_grid/topology.rs
src/grid/parallel_grid.rs
src/grid/single_element_grid.rs
src/grid/single_element_grid/builder.rs
src/grid/single_element_grid/grid.rs
src/grid/single_element_grid/parallel.rs
src/grid/single_element_grid/topology.rs
src/grid/traits.rs

Better implementation of MPI grids

---

src/grid/parallel_grid.rs

- Replace HashMaps with Vecs
- Treat points and vertices separately

Tidy parallel grid

---

src/element/ciarlet.rs

No more unsafe memory accesses

Use more RLST in element creation

---

Cargo.toml
benches/assembly_benchmark.rs
examples/assembly.rs
examples/test_parallel_assembly.rs
src/assembly.rs
src/assembly/batched.rs
src/assembly/batched/boundary.rs
src/assembly/batched/boundary/adjoint_double_layer.rs
src/assembly/batched/boundary/double_layer.rs
src/assembly/batched/boundary/hypersingular.rs
src/assembly/batched/boundary/single_layer.rs
src/assembly/batched/potential.rs
src/assembly/batched/potential/double_layer.rs
src/assembly/batched/potential/single_layer.rs
src/assembly/fmm_tools.rs
src/function/function_space.rs
src/function/function_space/parallel.rs
src/function/function_space/serial.rs
src/lib.rs
src/traits.rs
src/traits/function.rs
tests/compare_to_bempp_cl.rs
tests/fmm.rs.bak
tests/mixed_assembly.rs.bak

Reimplement parallel assembly

---

src/assembly/boundary/assemblers/hypersingular.rs
src/assembly/boundary/integrands.rs
src/assembly/boundary/integrands/hypersingular.rs

Move wavenumber out of HypersingularNormalNormalBoundaryIntegrand

---

src/assembly/boundary/assemblers.rs
src/assembly/boundary/cell_pair_assemblers.rs

Resolves #286. Progress towards #287.

Add cell pair assemblers with caching

---

Cargo.toml
src/assembly/boundary/cell_pair_assemblers.rs
src/assembly/boundary/integrands.rs
src/assembly/boundary/integrands/adjoint_double_layer.rs
src/assembly/boundary/integrands/double_layer.rs
src/assembly/boundary/integrands/hypersingular.rs
src/assembly/boundary/integrands/single_layer.rs
src/assembly/potential/cell_assemblers.rs
src/assembly/potential/integrands/double_layer.rs
src/assembly/potential/integrands/single_layer.rs
src/traits/assembly/boundary.rs
src/traits/assembly/potential.rs

Make BoundaryIntegrand trait unsafe
